stages:
  ingest:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/phishing_email.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  validate:
    cmd: python src/data_validation.py
    deps:
      - src/data_validation.py
      - data/processed/train.csv
      - data/processed/test.csv

  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/processed/train_clean.csv
      - data/processed/test_clean.csv

  transform:
    cmd: python src/data_transformation.py
    deps:
      - src/data_transformation.py
      - data/processed/train_clean.csv
      - data/processed/test_clean.csv
    outs:
      - models/vectorizer.pkl

  train:
    cmd: python src/model_trainer.py
    deps:
      - src/model_trainer.py
      - data/processed/train_clean.csv
      - models/vectorizer.pkl
    outs:
      - models/phishing_model.pkl

  evaluate:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/phishing_model.pkl
      - data/processed/test_clean.csv
